src/Switchboard.vala
* Cuddle else
* Whitespace
* Remove one-line method reset_title
* organize method build
=> Switchboard.vala: code style and organization

src/Switchboard.vala
=> Switchboard.vala: Curly brackets with if statements

src/Switchboard.vala
Now all the UI is built together nice and neat :)
=> Switchboard.vala: Get rid of setup_toolbar method

src/Switchboard.vala
This is only ever used in this one place
=> Switchboard.vala remove save state method

src/Widgets/CategoryFlowBox.vala, src/Widgets/CategoryIcon.vala
Updates the Free Software Foundation's address in license headers
Fixes #9
=> Update FSF address. Fixed #9

src/CategoryView.vala, src/PlugsSearch.vala, src/Switchboard.vala
Updates FSF address in license headers
=> Update fsf address

CMakeLists.txt, lib/Plug.vala, src/CategoryView.vala, src/Widgets/CategoryFlowBox.vala, src/Widgets/CategoryIcon.vala
This is much more reliable than the previous way and just works.
=> Handle plug visibility the right way

README.md
=> ReadMe: Add link to Valadoc

src/Switchboard.vala
=> Use GLib.Action accels for go back shortcut

meson.build
=> Use the right gettext domain

data/io.elementary.switchboard.gschema.xml, src/Switchboard.vala
Fixes #1 
Uses all the same changes we recently applied to Mail including more concise keys, changing on configure event throttled instead of on delete event, etc
=> Rewrite window state saving

README.md
Since it might not be obvious how to find the plugs from here
=> Link to plugs in README

meson.build, src/Application.vala
Also use action name on the button instead of a signal handler
=> Application: Add accel tooltip to back button

src/Widgets/CategoryIcon.vala
for a good time, view the diff with no whitespace changes
=> CategoryIcon: GObject style, inline namespace

src/Widgets/CategoryFlowBox.vala
Remove unused method while we're here
=> CategoryFlowBox: GObject-style construction

src/Application.vala, src/Widgets/CategoryFlowBox.vala
Fixes https://github.com/elementary/switchboard/issues/107
=> Fix keyboard navigation issue

debian/copyright
These files don't exist anymore
=> Copyright: remove outdated licenses etc

data/io.elementary.switchboard.appdata.xml.in
This does not contain a release tag intentionally
=> AppData: Add 2.3.7 info

data/io.elementary.switchboard.appdata.xml.in, meson.build
=> Release 2.3.7

src/Application.vala
=> Application: Remove dead code related to GCC

data/io.elementary.switchboard.appdata.xml.in, src/Application.vala, src/CategoryView.vala, src/Widgets/CategoryFlowBox.vala
Fixes #8 
Fixes #82 
Fixes some sizing issues and makes sure that everything in the top level stack is part of the navigation tree
=> Make AlertView internal to CategoryFlowBox

data/io.elementary.switchboard.appdata.xml.in, meson.build
=> Release 2.3.9

src/Application.vala
No logic changes, just getting rid of this single-use method
=> Application: remove build method

src/CategoryView.vala
Fixes #177 
Fixes #176 
Fixes #153
=> CategoryView: Add vertical scroll

README.md, meson.build, src/Application.vala
Fixes window dragging with latest Handy
=> Application: Use Hdy.Headerbar and Hdy.init

src/Application.vala
Minimum changes to replace Stack with Deck. This does not include swipe gestures
=> Application: Replace Stack with Hdy.Deck

src/Application.vala
Fixes #2 
Fixes #198 
Please let me know if anything here needs code comments to make it more clear what's happening
=> Application: Use Deck for Nav and allow swiping

src/Application.vala
Less stuff in the headerbar at a time for responsive
=> Application: center searchbox in categoryview

src/Application.vala, src/CategoryView.vala, src/SearchView.vala, src/Widgets/CategoryFlowBox.vala, src/Widgets/CategoryIcon.vala
=> Responsive

src/Application.vala, src/CategoryView.vala
=> Omit plug_selected signal

src/Application.vala
=> Application: don't load new plugs during a transition

.github/workflows/main.yml, sample/SamplePlug.vala
Build and install with `meson builddir --prefix=/usr -Dexample=true` for testing this
=> SamplePlug: Remove show_all for GTK 4

src/CategoryView.vala
=> Clamp category box, not scrolled window

src/Application.vala, src/CategoryView.vala, src/SearchView.vala
Fixes #270
Part 1 of my ultimate evil plan to flatten Settings: move the search bar and search page into the category view
=> CategoryView: absorb search bar

src/Application.vala
NavigationView already handles these accels, so just inform about them on the button, no need to set them again
=> Application: don't duplicate accel handling

data/styles/Index.scss, data/styles/Plug.scss, data/styles/SettingsSidebar.scss, lib/SettingsSidebar.vala
(most likely) Final pull before #279
=> SettingsSidebar: add a show_title_buttons option

data/styles/Index.scss, data/styles/Plug.scss, data/styles/SettingsSidebar.scss, lib/SettingsSidebar.vala
Adds styles for bottom toolbar in settings sidebars. Can be test with:
* https://github.com/elementary/switchboard-plug-notifications/pull/100
* https://github.com/elementary/switchboard-plug-printers/pull/202
=> SettinsgSidebar: Add styles for bottom bar

data/settings.gschema.xml
First step to solve #325, I understand that using Gtk.Paned is a standard for most Plugs, I’m adding this configuration to store the sidebar position.
=> Add Schema Sidebar Position

meson.build
=> meson: prepend prefix to BINDIR

data/settings.desktop.in, src/Application.vala
Fixes #355 
Add dbus.activation action and fallback exec
=> Add System Updates action
