elementary/switchboard

src/Switchboard.vala
Since we actually hide and show this widget it doesn't make sense for it to be insensitive while it's not shown :p
=> Switchboard.vala: don't set sensitive on back button

src/Switchboard.vala
Since we already hide/show the alert view with the stack we don't need to use hide/show properties on it
=> Switchboard.vala: simplify alert hide/show

src/Switchboard.vala
* Don't hide/show since we use stack
* Use set_visible_child_full instead of trying to identify transition type
* Remove obvious comments
=> Switchboard.vala: Simplify switch to icons

src/Switchboard.vala
It doesn't appear to be necessary  to expand these widgets
=> Switchboard.vala: Remove unnecessary expands

src/Switchboard.vala
This method is only used once, no need to declare variables for the whole class
=> Switchboard.vala: Remove restore method and simplify

src/Switchboard.vala
It appears that e140daf919f1cb5135fecd85ee76f3d877e0392e broke opening plugs from URL
=> Fix regression with showing plugs from URL

src/Switchboard.vala
Updates our compatibility layer so that 3rd party apps trying to open GCC will open the correct switchboard pane
=> Update GCC compat layer

src/Switchboard.vala
plug's hidden() method was not called when navigating back to another plug and when opening other with link  
i tested this with display plug ([related issue](https://github.com/elementary/switchboard-plug-display/issues/55)):
- got to Universal Access > Display > Display settings... now navigate back to Universal Access - display label on top left should not be shown
- open Displays than open some other settings with url, like settings://time - display label should hide
=> fix calling hidden()

src/Widgets/CategoryFlowBox.vala
Uses Granite.HeaderLabel instead of outdated `category-label` class
=> Use Granite.HeaderLabel

schemas/org.pantheon.switchboard.gschema.xml
I'm guessing this is a result of window sizes being calculated differently in a new mutter.
OLD:
NEW:
=> Change default window size

src/Widgets/CategoryFlowBox.vala
Fixes a bug that makes separators big and dumb
I tried to work around this in CSS, but it breaks other stuff. It looks like this is also broken in Adwaita, so it seems like Gtk+ doesn't expect separators to be filled in the wrong direction
(Gtk.Align.FILL is a bad default)
=> Valign category separators

src/Switchboard.vala
Not sure why we were adding a margin here in the first place
=> Switchboard.vala: fix deprecated methods

data/io.elementary.switchboard.desktop.in, meson.build
Fixes #6 
Changes the name of the binary (looks like everything else is already updated). Does not change the library name or plugs directory name
=> RDNN binary name

data/io.elementary.switchboard.appdata.xml.in
As indicated in the [spec](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html), this should prevent people from breaking their DE
=> AppData: Add compulsory for Pantheon

meson.build, meson_options.txt, src/Application.vala, src/meson.build
These only work while Switchboard is open, making them pretty useless.
=> Drop LibUnity quicklists

data/io.elementary.switchboard.appdata.xml.in, src/Widgets/CategoryFlowBox.vala
Makes the grid fill the space so its not cramped at the top of the display when maximized
Maximized on a small display
Tiled on a big display
Maximized on a big display
Maximized on a small display
=> CategoryFlowbox: vexpand everything

po/POTFILES, src/Application.vala, src/CategoryView.vala, src/SearchView.vala, src/Widgets/CategoryFlowBox.vala, src/meson.build
=> Add SearchView

data/io.elementary.switchboard.appdata.xml.in, src/Application.vala
* Move navkeys to a case statement since this is only used in one context
* Return `Gdk.EVENT_FOO` instead of true/false for clarity
* Connect to down key in the searchbox instead of the window so we don't have to check if the searchbox has focus
* Don't swallow tab key
=> Application: minor search cleanups

src/SearchView.vala
We now get the following error message on launching Switchboard:
```
(io.elementary.switchboard:31100): Gtk-CRITICAL **: 18:15:42.406: gtk_entry_get_text: assertion 'GTK_IS_ENTRY (entry)' failed
```
This is because `search_entry` is not initialized when [`SearchView.filter_func ()` is called](https://github.com/elementary/switchboard/blob/master/src/SearchView.vala#L35).
=> SearchView: Fix "assertion 'GTK_IS_ENTRY (entry)' failed" error

src/Application.vala
I'm pretty sure all of these are out of date and don't work. Regardless, this doesn't really cause any "breakage", Switchboard will just open to the category view
=> Application: Remove old GCC compat layer

src/Application.vala
Combine this single-use-method
Turns out we were setting search box sensitivity twice in a row here
=> Application: Remove switch_to_icons

src/Application.vala
We can't rely on the nav button being the only way panes are switched, especially not in the future when we're using Hdy.Deck. Instead, we listen to the stack to see if the child has changed and update accordingly.
This also ensures that `current_plug` is accurate
=> Application: Set title, search box, navbutton on visible-child.notify

lib/PlugsManager.vala
Use `GLib.ModuleFlags.LAZY` instead of `GLib.ModuleFlags.BIND_LAZY` which has been [deprecated since vala-0.46](https://valadoc.org/gmodule-2.0/GLib.ModuleFlags.BIND_LAZY.html)
=> PlugsManager: Use GLib.ModuleFlags.LAZY instead of deprecated BIND_LAZY

src/Application.vala
=> Fix 'All Settings' no longer be shown as translated

src/Application.vala
Swipe back is still not supported, but this ensures that we don't do anything until the deck finishes its transition (which we will need when we have swipes which can be cancelled)
=> Application: Update nav when deck finishes navigating

src/Application.vala
We set one whenever we set the other, so it doesn't make sense to have both
=> Application: Rely on opened_directly for transition

src/Application.vala
Make sure that we're actually checking an accurate list of the deck children to avoid adding duplicates
=> Application: Check actual children before adding duplicates

src/Application.vala
Because of these lines:
```
if (previous_plugs.size > 1) {
navigation_button.label = previous_plugs.@get (0).display_name;
previous_plugs.remove_at (previous_plugs.size - 1);
} else {
navigation_button.label = _(all_settings_label);
}
```
It's impossible for the back button to be anything other than `all_settings_label`  and `previous_plugs` to be smaller than 1. So we don't need to handle a case that isn't possible to get into.
This is also nice because now it means `switch_plug` is only called by `load_plug` and we can combine these
=> Application: Remove handler for impossible case

src/Application.vala
This forces Switchboard to use portals even though it's not in a sandbox. What this means practically is that Switchboard plugs will use the native file chooser instead of the one from Gtk
=> Application: force use portals

src/SearchView.vala
Instead of forcing a size with `width_chars` use `Adw.Clamp` to set a maximum size
=> SearchView: use clamp instead of width_chars

lib/Plug.vala
Supersedes #250
We don't use this in our plugs at least (if so that plug won't be shown; originally #250 intended to fix this issue), so it's safe to remove this. See also https://github.com/elementary/switchboard/pull/250#issuecomment-1295904284
=> Plug: Remove unused category other

lib/Plug.vala, src/Application.vala
Fixes the terminal warnings noted here: https://github.com/elementary/switchboard/pull/246#pullrequestreview-1119421015
As we only create one categoryview it is better to check the visible child type.  Using `==` did not seem to be working and as the category view has no associated plug the `else` clause was giving errors.
At present we can assume all leaflet children except the single categoryview have an associated plug.  Should this change the code here will have to be revisited.
Review without whitespace changes which got fixed in passing.
=> Fix terminal warning on navigate

debian/changelog, debian/control, debian/io.elementary.settings.install, debian/libswitchboard-2.0-0.install, debian/libswitchboard-2.0-dev.install, debian/libswitchboard-3-0.install, debian/libswitchboard-3-0.symbols, debian/libswitchboard-3-dev.install, debian/switchboard.install
Switches over the main packaging branch to build the Gtk4 version of System Settings. This is needed to fix the gettext action in `main`
I've pushed a branch `deb-packaging-jammy` that's a snapshot of the latest release for the 6.0 series
=> Changes for Gtk4 port

src/Application.vala
This window handle is blocking the context menu for wallpapers in https://github.com/elementary/switchboard-plug-pantheon-shell/pull/377
=> Application: remove big window handle

data/styles/SettingsPage.scss, lib/SettingsPage.vala
Avoid conflicting with the stylesheet for Granite.SimpleSettingsPage
=> SettingsPage: change css name

data/styles/SettingsPage.scss, lib/SettingsPage.vala
Instead of exposing the action area widget, add functions for adding start and end buttons like Gtk.Dialog. This also fixes an issue where the action area was always shown regardless of whether it had buttons in it.
Can test with https://github.com/elementary/switchboard-plug-locale/pull/187
=> SettingsPage: add functions for buttons

data/styles/CategoryView.scss, data/styles/Index.scss, src/Application.vala, src/CategoryView.vala, src/SearchView.vala
Review with "hide whitespace"
* Bump copyright header
* Inline namespace
* Set padding/margin with CSS
* Float searchbar
* Fix scrollbar location
* Reduce number of clamps, scrolled boxes, and stacks
* Make objects way more private
* Fix issues with search and keyboard nav
* Code style
* Remove an idle that caused plugs to load in late and make the view jump on launch every time
=> CategoryView: cleanup

lib/SettingsPage.vala
Sometimes we have dynamic descriptions so make sure can set descriptions outside of the constructor and we don't have to workaround by setting an empty string like:
https://github.com/elementary/switchboard-plug-bluetooth/pull/216/commits/b6a4ad411056c97163242c91d95ed6321d1f2a0f
=> SettingsPage: make description settable

data/styles/SettingsPage.scss, lib/SettingsPage.vala, lib/SettingsSidebarRow.vala
The only custom header widget we ever use is an Avatar, so add an option for that instead of the `display_widget` option which doesn't really work and isn't used
Can test with https://github.com/elementary/switchboard-plug-parental-controls/pull/187
Theoretically SettingsSidebarRow is also set up in this branch, but it'll take more work to make a branch to test that with so I'm assuming I'll need to follow up there to make it work properly
=> SettingsPage: add with_avatar option

data/styles/SettingsPage.scss, lib/SettingsPage.vala
Allow to optionally show end title buttons. Will be convenient for views like this:
We want it to be optional so we don't have duplicate window controls in situations like this:
=> SettingsPage: add option to show end title buttons

lib/SettingsSidebar.vala
* Fixes updating the sidebar when stack items change
* And make sure we don't set duplicate headers
Can be tested with https://github.com/elementary/switchboard-plug-parental-controls/pull/191
=> SettingsSidebar: bind stack model to list

data/styles/CategoryView.scss, data/styles/Plug.scss, src/CategoryView.vala
Saves us some view specific CSS and can be re-used in plugins where we have a stack switcher in the header
=> CategoryView: use a Adw.ToolbarView

data/styles/Plug.scss
Fixes an issue where we're clearing styles for toolbars that aren't in the toolbarview areas we want to clear such as actionbars inside a frame in keyboard settings
=> Plug.css: specifically target toolbars

src/Application.vala
It currently blocks pressing escape to discard setting a new shortcut in the keyboard plug.
=> Don't pop pages on escape

README.md
We now require sassc to build stylesheets.
=> README: Add sassc to dependencies

sample/SamplePlug.vala
This fixes the issue that you can't go back from the sample plug.
=> sample: Handle own titlebuttons

data/settings.appdata.xml.in, src/CategoryView.vala, src/SearchView.vala
=> Adding timeout to clear the search field

lib/SettingsSidebar.vala, lib/SettingsSidebarRow.vala
There was a mix up happening with settingspage title and the name of the visible child in the stack. This would cause e.g. when opening a plug for the first time via a search result the wrong result to show up. Also in further searches the wrong row would be selected. All of this is fixed now.
=> SettingsSideBar: Fix selection of the correct row

src/Application.vala
Now that we have Gtk.FileDialog which always uses the portal, we shouldn't set this any more
=> Application: don't set gtk_use_portal

lib/SettingsSidebar.vala, lib/SettingsSidebarRow.vala
Reverts elementary/switchboard#336
This is an API break and it breaks plugins that don't set stack page names, like in Sharing settings
=> Revert "SettingsSideBar: Fix selection of the correct row"
